services:
  app:
    build: .
    container_name: football_events_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: /app
  db:
    image: mysql:9.6.0
    container_name: football_events_app_db
    networks:
      - football_events_app
    environment:
      MYSQL_DATABASE: football_events_app
      MYSQL_USER: user
      MYSQL_PASSWORD: asdsad89a6d87A*(S7d987a09
      MYSQL_ROOT_PASSWORD: example

networks:
  football_events_app:
    name: football_events_app